export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS";
export const GET_CAMPAIGNS_FAILURE = "GET_CAMPAIGNS_FAILURE";
export const GET_CAMPAIGNS_ID = "GET_CAMPAIGNS_ID";

export const ADD_CAMPAIGNS_SUCCESS = "ADD_CAMPAIGNS_SUCCESS";
export const ADD_CAMPAIGNS_FAILURE = "ADD_CAMPAIGNS_FAILURE";

export const EDIT_CAMPAIGNS_SUCCESS = "EDIT_CAMPAIGNS_SUCCESS";
export const EDIT_CAMPAIGNS_FAILURE = "EDIT_CAMPAIGNS_FAILURE";

export const DELETE_CAMPAIGNS_SUCCESS = "DELETE_CAMPAIGNS_SUCCESS";
export const DELETE_CAMPAIGNS_FAILURE = "DELETE_CAMPAIGNS_FAILURE";


export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";


export const FETCH_BY_ID = "FETCH_BY_ID";

export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_FAILURE = "GET_ADMIN_FAILURE";

export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_FAILURE = "ADD_ADMIN_FAILURE";

export const EDIT_ADMIN_SUCCESS = "EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_FAILURE = "EDIT_ADMIN_FAILURE";

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAILURE = "DELETE_ADMIN_FAILURE";


export const GET_MANAGER_SUCCESS = "GET_MANAGER_SUCCESS";
export const GET_MANAGER_FAILURE = "GET_MANAGER_FAILURE";

export const ADD_MANAGER_SUCCESS = "ADD_MANAGER_SUCCESS ";
export const ADD_MANAGER_FAILURE = "ADD_MANAGER_FAILURE ";

export const EDIT_MANAGER_SUCCESS = "EDIT_MANAGER_SUCCESS";
export const EDIT_MANAGER_FAILURE = "EDIT_MANAGER_FAILURE";

export const DELETE_MANAGER_SUCCESS = "DELETE_MANAGER_SUCCESS";
export const DELETE_MANAGER_FAILURE = "DELETE_MANAGER_FAILURE";